### ISSUE TITLE
uv.h: No such file or directory

### ISSUE THREAD

**Issue by mkilivan** [oznu/node-pty-prebuilt-multiarch#15]
## Environment details

- OS: Yocto - Poky 
- OS version: Dunfell
- node-pty version: 0.9.0
- node version:  12.14.1
- node-gyp version: 5.0.5

## Issue description
I have built [homebridge-config-ui-x](https://www.npmjs.com/package/homebridge-config-ui-x)  version 4.29.0 in my own meta layer in a Yocto project. One of the dependencies or this npm package is _node-pty-prebuilt-multiarch_. 

```
"node-pty-prebuilt-multiarch": {
      "version": "0.9.0",
      "resolved": "https://registry.npmjs.org/node-pty-prebuilt-multiarch/-/node-pty-prebuilt-multiarch-0.9.0.tgz",
      "integrity": "sha512-n5LkPEuBwI+S2GgDk+IEByoVZClYFQGfp1b6dbMMEln7e43ikF8LZVi3vxpLXVq1rnS8t54YOnMB7HSB4jw8Tg==",
      "requires": {
        "nan": "^2.14.0",
        "prebuild-install": "^5.2.5"
      }
```

I got the following error on the build. It seems `uv.h` header file is missing. 
```
gyp verb build/config.gypi writing out config file: /yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/npm-build/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/build/config.gypi
gyp verb config.gypi checking for gypi file: /yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/npm-build/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/config.gypi
gyp verb common.gypi checking for gypi file: /yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/npm-build/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /yocto-downloads/poky/build/tmp/hosttools/python
gyp info spawn args [
gyp info spawn args   '/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/npm-build/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr',
gyp info spawn args   '-Dnode_gyp_dir=/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr/$(Configuration)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/npm-build/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture arm
gyp verb node dev dir /yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr
gyp verb `which` succeeded for `make` /yocto-downloads/poky/build/tmp/hosttools/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
In file included from ../src/unix/pty.cc:20:
../../nan/nan.h:55:10: fatal error: uv.h: No such file or directory
   55 | #include <uv.h>
      |          ^~~~~~
compilation terminated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-120-generic
gyp ERR! command "/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr/bin/node" "/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/npm-build/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm verb lifecycle node-pty-prebuilt-multiarch@0.9.0~install: unsafe-perm in lifecycle true
npm verb lifecycle node-pty-prebuilt-multiarch@0.9.0~install: PATH: /yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/npm-build/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/node_modules/.bin:/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/npm-build/lib/node_modules/homebridge-config-ui-x/node_modules/.bin:/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/npm-build/lib/node_modules/.bin:/yocto-downloads/poky/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/yocto-downloads/poky/scripts:/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi:/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot/usr/bin/crossscripts:/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr/sbin:/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr/bin:/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/sbin:/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/bin:/yocto-downloads/poky/bitbake/bin:/yocto-downloads/poky/build/tmp/hosttools
npm verb lifecycle node-pty-prebuilt-multiarch@0.9.0~install: CWD: /yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/npm-build/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch
npm sill lifecycle node-pty-prebuilt-multiarch@0.9.0~install: Args: [ '-c', 'prebuild-install || node scripts/install.js' ]
npm sill lifecycle node-pty-prebuilt-multiarch@0.9.0~install: Returned: code: 1  signal: null
npm info lifecycle node-pty-prebuilt-multiarch@0.9.0~install: Failed to exec install script
npm timing action:install Completed in 5787ms
npm verb unlock done using /yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/npm-cache/_locks/staging-baa2633533be2f58.lock for /yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/npm-build/lib/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 1233ms
npm timing stage:runTopLevelLifecycles Completed in 12472ms
npm verb stack Error: node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:223:5)
npm verb stack     at ChildProcess.<anonymous> (/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:223:5)
npm verb stack     at maybeClose (internal/child_process.js:1021:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
npm verb pkgid node-pty-prebuilt-multiarch@0.9.0
npm verb cwd /tmp/tmps82fq5o_
npm verb Linux 4.15.0-120-generic
npm verb argv "/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr/bin/node" "/yocto-downloads/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/homebridge-config-ui-x/4.29.0-r0/recipe-sysroot-native/usr/bin/npm" "install" "/tmp/tmp3nbz26e7/homebridge-config-ui-x-4.29.0.tgz" "--target_arch=arm" "--build-from-source=true"
npm verb node v12.14.1
npm verb npm  v6.13.4
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
```

Do you have any idea what might be wrong?

Thanks

**Comment by mkilivan** [comment]
Adding `libuv` as a build-time dependency in the recipe solves the issue. 
```
DEPENDS = "libuv"
```
